LANDING_MULTIPLIER = 1000
TOUCHDOWN_MULTIPLIER = 20
NOT_ON_CENTER_RUNWAY_MULTIPLIER = 1
NEGATIVE_REWARD = -50
PITCH_BEFORE_LANDING_MULTIPLIER = 2
OVER_GROUND_PITCH_REWARD = 5


ON_GROUND_MULTIPLIER = 1
BEARING_MULTIPLIER = 10
SPEED_BEFORE_LANDING_MULTIPLIER = 40
