DAMAGE_MULTIPLIER = 1000
LANDING_MULTIPLIER = 5000
LANDING_SPEED_MULTIPLIER = 20
DISTANCE_MULTIPLIER = 3
ALTITUDE_MULTIPLIER = 5
DISCREPANCY_MULTIPLIER = 10
DISCREPANCY_RESET_MULTIPLIER = 1000
BEARING_MULTIPLIER = 10
PITCH_MULTIPLIER = 5
TOUCHDOWN_MULTIPLIER = 800
NOT_ON_RUNWAY_MULTIPLIER = 2000

NEGATIVE_REWARD = -1000

